### ISSUE TITLE
Vinmeen HD

### ISSUE THREAD

**Issue by naveenland4** [EekJack/MyKodi#2]
Hi Pls add Ass-Tro Vinmeen HD Channel also if possible.

TIA

**Comment by EekJack** [comment]
ok boss.. i try my best,... maybe next month i move  my play list to other
domain.. cause i see someone sell it on shopee.

**Comment by EekJack** [comment]
https://gist.githubusercontent.com/EekJack/dd1f366904d85f7ba10d9690263279b9/raw/0aee49eb3d45a3bb52e7a7975bdb1e906efb98aa/m3u8

my github repositories will be deleted next week, after sabah vs jdt
match😁😁
fill free to contact me for my new gist link if intrested.. thanks

sorry for my bad english.

**Comment by naveenland4** [comment]
Thanks bro. Pls delete the gist link i have added into my ott navigator. Thanks for your help
